import type { ThemeConfig, ThemeMode } from '@calculo/shared';

export const themes: Record<ThemeMode, ThemeConfig> = {
  dark: {
    mode: 'dark',
    primaryColor: '#3b82f6',
    backgroundColor: '#0a0a0b',
    textColor: '#fafafa',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 8,
    spacing: 4,
  },
  light: {
    mode: 'light',
    primaryColor: '#3b82f6',
    backgroundColor: '#ffffff',
    textColor: '#0a0a0b',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 8,
    spacing: 4,
  },
  oled: {
    mode: 'oled',
    primaryColor: '#6366f1',
    backgroundColor: '#000000',
    textColor: '#ffffff',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 4,
    spacing: 4,
  },
  'high-contrast': {
    mode: 'high-contrast',
    primaryColor: '#ffff00',
    backgroundColor: '#000000',
    textColor: '#ffffff',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 0,
    spacing: 4,
  },
  glass: {
    mode: 'glass',
    primaryColor: '#8b5cf6',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    textColor: '#ffffff',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 16,
    spacing: 4,
  },
  neumorphism: {
    mode: 'neumorphism',
    primaryColor: '#6366f1',
    backgroundColor: '#e0e5ec',
    textColor: '#2d3748',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 16,
    spacing: 4,
  },
  minimal: {
    mode: 'minimal',
    primaryColor: '#000000',
    backgroundColor: '#ffffff',
    textColor: '#000000',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: 0,
    spacing: 2,
  },
  corporate: {
    mode: 'corporate',
    primaryColor: '#1e40af',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: 4,
    spacing: 4,
  },
  custom: {
    mode: 'custom',
    primaryColor: '#3b82f6',
    backgroundColor: '#0a0a0b',
    textColor: '#fafafa',
    fontFamily: 'Geist, system-ui, sans-serif',
    borderRadius: 8,
    spacing: 4,
  },
};
